language: php

sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - SYMFONY_VERSION="2.3.*"
    - SYMFONY_VERSION="2.7.*"
    - SYMFONY_VERSION="2.8.*"
    - SYMFONY_VERSION="3.0.*"
    - SYMFONY_VERSION="3.1.*"
    - SYMFONY_VERSION="3.2.*"
    - SYMFONY_VERSION="3.3.*"
    - SYMFONY_VERSION="3.4.*"

matrix:
    exclude:
        - php: 5.4
          env: SYMFONY_VERSION="3.0.*"
        - php: 5.4
          env: SYMFONY_VERSION="3.1.*"
        - php: 5.4
          env: SYMFONY_VERSION="3.2.*"
        - php: 5.4
          env: SYMFONY_VERSION="3.3.*"
        - php: 5.4
          env: SYMFONY_VERSION="3.4.*"
        - php: 5.4
          env: SYMFONY_VERSION="3.2.*"

install:
    - 'composer --prefer-dist require symfony/framework-bundle:"${SYMFONY_VERSION}"'

script:
    - vendor/bin/phpunit -v

after_script:
     - ./vendor/bin/test-reporter
