parameters:
    router.class: PiotrPolak\ConditionalRoutingBundle\Router\ConditionalRouter

services:
    conditional_router.routing_loader:
        class: PiotrPolak\ConditionalRoutingBundle\Router\ConditionalRoutesLoader
        tags:
            - { name: routing.loader }
