parameters:
    router.class: Piotrpolak\ConditionalRoutingBundle\Router\ConditionalRouter

services:
    conditional_loader:
        class: Test\CustomBundle\Router\CustomRoutesLoader
        tags:
            - { name: routing.loader }
